import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { MOCK_BOOTSTRAP_PAYLOAD, MOCK_HEALTH_PAYLOAD } from "../public/model-contract.mjs";

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const publicRoot = path.join(projectRoot, "public");
const distRoot = path.join(projectRoot, "dist");
const clientRoot = path.join(distRoot, "client");
const serverRoot = path.join(distRoot, "server");
const requiredFiles = ["index.html", "styles.css", "app.js", "domain.mjs", "api-adapter.mjs", "model-contract.mjs"];

const contentTypes = new Map([
  [".avif", "image/avif"],
  [".css", "text/css; charset=utf-8"],
  [".gif", "image/gif"],
  [".html", "text/html; charset=utf-8"],
  [".ico", "image/x-icon"],
  [".jpeg", "image/jpeg"],
  [".jpg", "image/jpeg"],
  [".js", "text/javascript; charset=utf-8"],
  [".json", "application/json; charset=utf-8"],
  [".mjs", "text/javascript; charset=utf-8"],
  [".mp4", "video/mp4"],
  [".pdf", "application/pdf"],
  [".png", "image/png"],
  [".svg", "image/svg+xml; charset=utf-8"],
  [".txt", "text/plain; charset=utf-8"],
  [".webmanifest", "application/manifest+json; charset=utf-8"],
  [".webp", "image/webp"],
  [".woff", "font/woff"],
  [".woff2", "font/woff2"],
  [".xml", "application/xml; charset=utf-8"],
]);

async function assertPublicSource() {
  const publicStats = await stat(publicRoot).catch(() => null);
  if (!publicStats?.isDirectory()) {
    throw new Error(`Static source directory was not found: ${publicRoot}`);
  }

  const missing = [];
  for (const relativePath of requiredFiles) {
    const fileStats = await stat(path.join(publicRoot, relativePath)).catch(() => null);
    if (!fileStats?.isFile()) missing.push(relativePath);
  }

  if (missing.length > 0) {
    throw new Error(`public/ is missing required files: ${missing.join(", ")}`);
  }
}

async function collectFiles(directory, current = directory) {
  const entries = await readdir(current, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolutePath = path.join(current, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await collectFiles(directory, absolutePath)));
    } else if (entry.isFile()) {
      files.push(absolutePath);
    }
  }

  return files.sort((left, right) => left.localeCompare(right));
}

function createWorkerSource(manifest) {
  return `// Generated by scripts/build.mjs. Do not edit directly.
const embeddedAssets = ${JSON.stringify(manifest)};
const mockHealthPayload = ${JSON.stringify(MOCK_HEALTH_PAYLOAD)};
const mockBootstrapPayload = ${JSON.stringify(MOCK_BOOTSTRAP_PAYLOAD)};

function decodeBase64(value) {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

function embeddedResponse(asset, method) {
  const headers = new Headers({
    "content-type": asset.contentType,
    "cache-control": asset.isDocument
      ? "no-cache"
      : "public, max-age=3600, must-revalidate",
  });
  return new Response(method === "HEAD" ? null : decodeBase64(asset.body), {
    status: 200,
    headers,
  });
}

function requestedAssetPath(request) {
  let pathname;
  try {
    pathname = decodeURIComponent(new URL(request.url).pathname);
  } catch {
    return null;
  }
  if (pathname === "/") return "/index.html";
  return pathname;
}

function jsonResponse(payload, method, status = 200) {
  return new Response(method === "HEAD" ? null : JSON.stringify(payload), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}

export default {
  async fetch(request, env = {}) {
    if (request.method !== "GET" && request.method !== "HEAD") {
      return new Response("Method Not Allowed", {
        status: 405,
        headers: { allow: "GET, HEAD" },
      });
    }

    const pathname = new URL(request.url).pathname;
    if (pathname === "/api/health") {
      return jsonResponse(mockHealthPayload, request.method);
    }
    if (pathname === "/api/mock/bootstrap") {
      return jsonResponse(mockBootstrapPayload, request.method);
    }

    const assetPath = requestedAssetPath(request);
    const embedded = assetPath && embeddedAssets[assetPath];
    if (embedded) return embeddedResponse(embedded, request.method);

    if (env.ASSETS && typeof env.ASSETS.fetch === "function") {
      return env.ASSETS.fetch(request);
    }

    return new Response("Not Found", {
      status: 404,
      headers: { "content-type": "text/plain; charset=utf-8" },
    });
  },
};
`;
}

await assertPublicSource();
await rm(distRoot, { recursive: true, force: true });
await mkdir(clientRoot, { recursive: true });
await cp(publicRoot, clientRoot, { recursive: true, force: true });

const files = await collectFiles(clientRoot);
const manifest = {};
for (const absolutePath of files) {
  const relativePath = path.relative(clientRoot, absolutePath).split(path.sep).join("/");
  const extension = path.extname(relativePath).toLowerCase();
  manifest[`/${relativePath}`] = {
    body: (await readFile(absolutePath)).toString("base64"),
    contentType: contentTypes.get(extension) ?? "application/octet-stream",
    isDocument: extension === ".html",
  };
}

await mkdir(serverRoot, { recursive: true });
await writeFile(path.join(serverRoot, "index.js"), createWorkerSource(manifest), "utf8");

console.log(
  `Built ${files.length} static files (${Object.keys(manifest).length} embedded) into ${path.relative(projectRoot, distRoot)}/`,
);
